
export const GET_PRODUCT_DATA           = 'GET_PRODUCT_DATA';
export const GET_PRODUCT_DATA_BEGIN     = 'GET_PRODUCT_DATA_BEGIN';
export const GET_PRODUCT_DATA_SUCCESS   = 'GET_PRODUCT_DATA_SUCCESS';
export const GET_PRODUCT_DATA_FAILURE   = 'GET_PRODUCT_DATA_FAILURE';


export const GET_FULLPRODUCTITEM_DATA           = 'GET_FULLPRODUCTITEM_DATA';
export const GET_FULLPRODUCTITEM_DATA_BEGIN     = 'GET_FULLPRODUCTITEM_DATA_BEGIN';
export const GET_FULLPRODUCTITEM_DATA_SUCCESS   = 'GET_FULLPRODUCTITEM_DATA_SUCCESS';
export const GET_FULLPRODUCTITEM_DATA_FAILURE   = 'GET_FULLPRODUCTITEM_DATA_FAILURE';

